// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dlVisited.proto

package dlVisited

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPointsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Vid                  int64    `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointsRequest) Reset()         { *m = GetPointsRequest{} }
func (m *GetPointsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPointsRequest) ProtoMessage()    {}
func (*GetPointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75e4e7b7794c4e27, []int{0}
}

func (m *GetPointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointsRequest.Unmarshal(m, b)
}
func (m *GetPointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointsRequest.Marshal(b, m, deterministic)
}
func (m *GetPointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointsRequest.Merge(m, src)
}
func (m *GetPointsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPointsRequest.Size(m)
}
func (m *GetPointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointsRequest proto.InternalMessageInfo

func (m *GetPointsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetPointsRequest) GetVid() int64 {
	if m != nil {
		return m.Vid
	}
	return 0
}

type GetPointsResponse struct {
	Status               uint32          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64           `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Points               []*PointInfoMsg `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetPointsResponse) Reset()         { *m = GetPointsResponse{} }
func (m *GetPointsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPointsResponse) ProtoMessage()    {}
func (*GetPointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75e4e7b7794c4e27, []int{1}
}

func (m *GetPointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointsResponse.Unmarshal(m, b)
}
func (m *GetPointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointsResponse.Marshal(b, m, deterministic)
}
func (m *GetPointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointsResponse.Merge(m, src)
}
func (m *GetPointsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPointsResponse.Size(m)
}
func (m *GetPointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointsResponse proto.InternalMessageInfo

func (m *GetPointsResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetPointsResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetPointsResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GetPointsResponse) GetPoints() []*PointInfoMsg {
	if m != nil {
		return m.Points
	}
	return nil
}

type PointInfoMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	SpecialWords         string   `protobuf:"bytes,5,opt,name=specialWords,proto3" json:"specialWords,omitempty"`
	Long                 float32  `protobuf:"fixed32,6,opt,name=long,proto3" json:"long,omitempty"`
	Lat                  float32  `protobuf:"fixed32,7,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointInfoMsg) Reset()         { *m = PointInfoMsg{} }
func (m *PointInfoMsg) String() string { return proto.CompactTextString(m) }
func (*PointInfoMsg) ProtoMessage()    {}
func (*PointInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_75e4e7b7794c4e27, []int{2}
}

func (m *PointInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointInfoMsg.Unmarshal(m, b)
}
func (m *PointInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointInfoMsg.Marshal(b, m, deterministic)
}
func (m *PointInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointInfoMsg.Merge(m, src)
}
func (m *PointInfoMsg) XXX_Size() int {
	return xxx_messageInfo_PointInfoMsg.Size(m)
}
func (m *PointInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PointInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PointInfoMsg proto.InternalMessageInfo

func (m *PointInfoMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PointInfoMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PointInfoMsg) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PointInfoMsg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PointInfoMsg) GetSpecialWords() string {
	if m != nil {
		return m.SpecialWords
	}
	return ""
}

func (m *PointInfoMsg) GetLong() float32 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *PointInfoMsg) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type GetPointDescRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Vid                  int64    `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointDescRequest) Reset()         { *m = GetPointDescRequest{} }
func (m *GetPointDescRequest) String() string { return proto.CompactTextString(m) }
func (*GetPointDescRequest) ProtoMessage()    {}
func (*GetPointDescRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75e4e7b7794c4e27, []int{3}
}

func (m *GetPointDescRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointDescRequest.Unmarshal(m, b)
}
func (m *GetPointDescRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointDescRequest.Marshal(b, m, deterministic)
}
func (m *GetPointDescRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointDescRequest.Merge(m, src)
}
func (m *GetPointDescRequest) XXX_Size() int {
	return xxx_messageInfo_GetPointDescRequest.Size(m)
}
func (m *GetPointDescRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointDescRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointDescRequest proto.InternalMessageInfo

func (m *GetPointDescRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetPointDescRequest) GetVid() int64 {
	if m != nil {
		return m.Vid
	}
	return 0
}

type GetPointDescResponse struct {
	Status               uint32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64         `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	PointInfo            *PointInfoMsg `protobuf:"bytes,4,opt,name=pointInfo,proto3" json:"pointInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPointDescResponse) Reset()         { *m = GetPointDescResponse{} }
func (m *GetPointDescResponse) String() string { return proto.CompactTextString(m) }
func (*GetPointDescResponse) ProtoMessage()    {}
func (*GetPointDescResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75e4e7b7794c4e27, []int{4}
}

func (m *GetPointDescResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointDescResponse.Unmarshal(m, b)
}
func (m *GetPointDescResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointDescResponse.Marshal(b, m, deterministic)
}
func (m *GetPointDescResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointDescResponse.Merge(m, src)
}
func (m *GetPointDescResponse) XXX_Size() int {
	return xxx_messageInfo_GetPointDescResponse.Size(m)
}
func (m *GetPointDescResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointDescResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointDescResponse proto.InternalMessageInfo

func (m *GetPointDescResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetPointDescResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetPointDescResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GetPointDescResponse) GetPointInfo() *PointInfoMsg {
	if m != nil {
		return m.PointInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPointsRequest)(nil), "GetPointsRequest")
	proto.RegisterType((*GetPointsResponse)(nil), "GetPointsResponse")
	proto.RegisterType((*PointInfoMsg)(nil), "PointInfoMsg")
	proto.RegisterType((*GetPointDescRequest)(nil), "GetPointDescRequest")
	proto.RegisterType((*GetPointDescResponse)(nil), "GetPointDescResponse")
}

func init() { proto.RegisterFile("dlVisited.proto", fileDescriptor_75e4e7b7794c4e27) }

var fileDescriptor_75e4e7b7794c4e27 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x6d, 0x76, 0xdb, 0x2d, 0x3b, 0xb6, 0xda, 0xc6, 0x2a, 0xa1, 0xa7, 0x25, 0x20, 0x2c, 0x08,
	0x7b, 0xa8, 0x9e, 0x84, 0xde, 0x04, 0xf1, 0x20, 0x48, 0x0e, 0x7a, 0xae, 0xdd, 0x58, 0x82, 0xdb,
	0x64, 0x6d, 0x52, 0xf1, 0xa8, 0xff, 0xe3, 0x47, 0x4a, 0xa6, 0xed, 0xba, 0xb5, 0xbd, 0x08, 0xde,
	0xde, 0x64, 0x78, 0x33, 0xf3, 0x5e, 0x1e, 0x1c, 0xe5, 0xc5, 0x83, 0xb2, 0xca, 0xc9, 0x3c, 0x2b,
	0x17, 0xc6, 0x19, 0x7e, 0x05, 0xbd, 0x1b, 0xe9, 0xee, 0x8d, 0xd2, 0xce, 0x0a, 0xf9, 0xba, 0x94,
	0xd6, 0xd1, 0x01, 0xb4, 0x9c, 0x79, 0x91, 0x9a, 0x91, 0x84, 0xa4, 0xb1, 0x58, 0x15, 0xb4, 0x07,
	0xe1, 0x9b, 0xca, 0x59, 0x90, 0x90, 0x34, 0x14, 0x1e, 0xf2, 0x77, 0xe8, 0xd7, 0xb8, 0xb6, 0x34,
	0xda, 0x4a, 0x7a, 0x0a, 0x91, 0x75, 0x13, 0xb7, 0xb4, 0xc8, 0xee, 0x8a, 0x75, 0xe5, 0xe9, 0x73,
	0x3b, 0x43, 0x7a, 0x2c, 0x3c, 0xa4, 0x14, 0x9a, 0x4e, 0xcd, 0x25, 0x0b, 0x71, 0x22, 0x62, 0x7a,
	0x06, 0x51, 0x89, 0xf3, 0x58, 0x33, 0x09, 0xd3, 0x83, 0x51, 0x37, 0xc3, 0xf1, 0xb7, 0xfa, 0xd9,
	0xdc, 0xd9, 0x99, 0x58, 0x37, 0xf9, 0x17, 0x81, 0x4e, 0xbd, 0x41, 0x0f, 0x21, 0x50, 0x39, 0x6e,
	0x0c, 0x45, 0xa0, 0x72, 0xca, 0xa0, 0x3d, 0x35, 0xda, 0x49, 0xed, 0xd6, 0x1b, 0x37, 0x25, 0x8a,
	0x53, 0xae, 0x58, 0xad, 0xf5, 0xe2, 0x7c, 0x51, 0xdd, 0xd2, 0xac, 0xdd, 0xc2, 0xa1, 0x63, 0x4b,
	0x39, 0x55, 0x93, 0xe2, 0xd1, 0x2c, 0x72, 0xcb, 0x5a, 0x48, 0xd8, 0x7a, 0xf3, 0xbc, 0xc2, 0xe8,
	0x19, 0x8b, 0x12, 0x92, 0x06, 0x02, 0xb1, 0x57, 0x5a, 0x4c, 0x1c, 0x6b, 0xe3, 0x93, 0x87, 0x7c,
	0x0c, 0xc7, 0x1b, 0xa3, 0xae, 0xa5, 0x9d, 0xfe, 0xd5, 0xe7, 0x4f, 0x02, 0x83, 0x6d, 0xfe, 0xbf,
	0x78, 0x7d, 0x0e, 0x71, 0xb9, 0xf1, 0x10, 0x85, 0xef, 0xd8, 0xfd, 0xd3, 0x1f, 0x7d, 0x10, 0x88,
	0xab, 0xec, 0xd0, 0x4b, 0x88, 0xab, 0x9f, 0xa7, 0xfd, 0xec, 0x77, 0x82, 0x86, 0x34, 0xdb, 0x09,
	0x06, 0x6f, 0xd0, 0x31, 0x74, 0xea, 0x32, 0xe8, 0x20, 0xdb, 0xe3, 0xca, 0xf0, 0x24, 0xdb, 0xa7,
	0x95, 0x37, 0x9e, 0x22, 0x4c, 0xec, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x83, 0x52,
	0xcd, 0xc4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DlVisited service

type DlVisitedClient interface {
	GetPoints(ctx context.Context, in *GetPointsRequest, opts ...client.CallOption) (*GetPointsResponse, error)
	GetPointDesc(ctx context.Context, in *GetPointDescRequest, opts ...client.CallOption) (*GetPointDescResponse, error)
}

type dlVisitedClient struct {
	c           client.Client
	serviceName string
}

func NewDlVisitedClient(serviceName string, c client.Client) DlVisitedClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "dlvisited"
	}
	return &dlVisitedClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dlVisitedClient) GetPoints(ctx context.Context, in *GetPointsRequest, opts ...client.CallOption) (*GetPointsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DlVisited.GetPoints", in)
	out := new(GetPointsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dlVisitedClient) GetPointDesc(ctx context.Context, in *GetPointDescRequest, opts ...client.CallOption) (*GetPointDescResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DlVisited.GetPointDesc", in)
	out := new(GetPointDescResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DlVisited service

type DlVisitedHandler interface {
	GetPoints(context.Context, *GetPointsRequest, *GetPointsResponse) error
	GetPointDesc(context.Context, *GetPointDescRequest, *GetPointDescResponse) error
}

func RegisterDlVisitedHandler(s server.Server, hdlr DlVisitedHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DlVisited{hdlr}, opts...))
}

type DlVisited struct {
	DlVisitedHandler
}

func (h *DlVisited) GetPoints(ctx context.Context, in *GetPointsRequest, out *GetPointsResponse) error {
	return h.DlVisitedHandler.GetPoints(ctx, in, out)
}

func (h *DlVisited) GetPointDesc(ctx context.Context, in *GetPointDescRequest, out *GetPointDescResponse) error {
	return h.DlVisitedHandler.GetPointDesc(ctx, in, out)
}
