// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dlMsgBoard.proto

package dlMsgBoard

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishMsgRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Bid                  int64    `protobuf:"varint,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsPublic             bool     `protobuf:"varint,4,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMsgRequest) Reset()         { *m = PublishMsgRequest{} }
func (m *PublishMsgRequest) String() string { return proto.CompactTextString(m) }
func (*PublishMsgRequest) ProtoMessage()    {}
func (*PublishMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0ccd5879b2632ce, []int{0}
}

func (m *PublishMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMsgRequest.Unmarshal(m, b)
}
func (m *PublishMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMsgRequest.Marshal(b, m, deterministic)
}
func (m *PublishMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMsgRequest.Merge(m, src)
}
func (m *PublishMsgRequest) XXX_Size() int {
	return xxx_messageInfo_PublishMsgRequest.Size(m)
}
func (m *PublishMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMsgRequest proto.InternalMessageInfo

func (m *PublishMsgRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PublishMsgRequest) GetBid() int64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *PublishMsgRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PublishMsgRequest) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

type PublishMsgResponse struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMsgResponse) Reset()         { *m = PublishMsgResponse{} }
func (m *PublishMsgResponse) String() string { return proto.CompactTextString(m) }
func (*PublishMsgResponse) ProtoMessage()    {}
func (*PublishMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0ccd5879b2632ce, []int{1}
}

func (m *PublishMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMsgResponse.Unmarshal(m, b)
}
func (m *PublishMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMsgResponse.Marshal(b, m, deterministic)
}
func (m *PublishMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMsgResponse.Merge(m, src)
}
func (m *PublishMsgResponse) XXX_Size() int {
	return xxx_messageInfo_PublishMsgResponse.Size(m)
}
func (m *PublishMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMsgResponse proto.InternalMessageInfo

func (m *PublishMsgResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PublishMsgResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PublishMsgResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MsgInfoMsg struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Publisher            string   `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgInfoMsg) Reset()         { *m = MsgInfoMsg{} }
func (m *MsgInfoMsg) String() string { return proto.CompactTextString(m) }
func (*MsgInfoMsg) ProtoMessage()    {}
func (*MsgInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0ccd5879b2632ce, []int{2}
}

func (m *MsgInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgInfoMsg.Unmarshal(m, b)
}
func (m *MsgInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgInfoMsg.Marshal(b, m, deterministic)
}
func (m *MsgInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInfoMsg.Merge(m, src)
}
func (m *MsgInfoMsg) XXX_Size() int {
	return xxx_messageInfo_MsgInfoMsg.Size(m)
}
func (m *MsgInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInfoMsg proto.InternalMessageInfo

func (m *MsgInfoMsg) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgInfoMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MsgInfoMsg) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *MsgInfoMsg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetMsgRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StartLine            int64    `protobuf:"varint,2,opt,name=startLine,proto3" json:"startLine,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMsgRequest) Reset()         { *m = GetMsgRequest{} }
func (m *GetMsgRequest) String() string { return proto.CompactTextString(m) }
func (*GetMsgRequest) ProtoMessage()    {}
func (*GetMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0ccd5879b2632ce, []int{3}
}

func (m *GetMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMsgRequest.Unmarshal(m, b)
}
func (m *GetMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMsgRequest.Marshal(b, m, deterministic)
}
func (m *GetMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMsgRequest.Merge(m, src)
}
func (m *GetMsgRequest) XXX_Size() int {
	return xxx_messageInfo_GetMsgRequest.Size(m)
}
func (m *GetMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMsgRequest proto.InternalMessageInfo

func (m *GetMsgRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetMsgRequest) GetStartLine() int64 {
	if m != nil {
		return m.StartLine
	}
	return 0
}

func (m *GetMsgRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetMsgResponse struct {
	Status               uint32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64         `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	MsgInfo              []*MsgInfoMsg `protobuf:"bytes,4,rep,name=msgInfo,proto3" json:"msgInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMsgResponse) Reset()         { *m = GetMsgResponse{} }
func (m *GetMsgResponse) String() string { return proto.CompactTextString(m) }
func (*GetMsgResponse) ProtoMessage()    {}
func (*GetMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0ccd5879b2632ce, []int{4}
}

func (m *GetMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMsgResponse.Unmarshal(m, b)
}
func (m *GetMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMsgResponse.Marshal(b, m, deterministic)
}
func (m *GetMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMsgResponse.Merge(m, src)
}
func (m *GetMsgResponse) XXX_Size() int {
	return xxx_messageInfo_GetMsgResponse.Size(m)
}
func (m *GetMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMsgResponse proto.InternalMessageInfo

func (m *GetMsgResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMsgResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetMsgResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GetMsgResponse) GetMsgInfo() []*MsgInfoMsg {
	if m != nil {
		return m.MsgInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishMsgRequest)(nil), "PublishMsgRequest")
	proto.RegisterType((*PublishMsgResponse)(nil), "PublishMsgResponse")
	proto.RegisterType((*MsgInfoMsg)(nil), "MsgInfoMsg")
	proto.RegisterType((*GetMsgRequest)(nil), "GetMsgRequest")
	proto.RegisterType((*GetMsgResponse)(nil), "GetMsgResponse")
}

func init() { proto.RegisterFile("dlMsgBoard.proto", fileDescriptor_f0ccd5879b2632ce) }

var fileDescriptor_f0ccd5879b2632ce = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4b, 0x6b, 0xc2, 0x40,
	0x10, 0x36, 0x8f, 0xaa, 0x19, 0xd1, 0xda, 0x69, 0x29, 0x41, 0x3c, 0x84, 0x40, 0x21, 0x50, 0xc8,
	0xc1, 0x1e, 0x7a, 0xef, 0xa5, 0x14, 0x1a, 0x28, 0x7b, 0xed, 0x49, 0xcd, 0x1a, 0x43, 0x75, 0x57,
	0x33, 0x93, 0xff, 0x5f, 0xb2, 0x89, 0xc6, 0xe0, 0xa1, 0x97, 0xde, 0xe6, 0x9b, 0x5d, 0xe6, 0x7b,
	0xcc, 0xc0, 0x34, 0xdd, 0x25, 0x94, 0xbd, 0xe9, 0x65, 0x91, 0xc6, 0x87, 0x42, 0xb3, 0x0e, 0x8f,
	0x70, 0xf7, 0x55, 0xae, 0x76, 0x39, 0x6d, 0x13, 0xca, 0x84, 0x3c, 0x96, 0x92, 0x18, 0x1f, 0xe0,
	0x86, 0xf5, 0x8f, 0x54, 0xbe, 0x15, 0x58, 0x91, 0x27, 0x6a, 0x80, 0x53, 0x70, 0x56, 0x79, 0xea,
	0xdb, 0x81, 0x15, 0x39, 0xa2, 0x2a, 0xd1, 0x87, 0xc1, 0x5a, 0x2b, 0x96, 0x8a, 0x7d, 0xc7, 0xfc,
	0x3c, 0x41, 0x9c, 0xc1, 0x30, 0x27, 0x33, 0x78, 0xed, 0xbb, 0x81, 0x15, 0x0d, 0xc5, 0x19, 0x87,
	0x02, 0xf0, 0x92, 0x92, 0x0e, 0x5a, 0x91, 0xc4, 0x47, 0xe8, 0x13, 0x2f, 0xb9, 0x24, 0x43, 0x3a,
	0x16, 0x0d, 0xaa, 0x58, 0xf7, 0x94, 0x19, 0x56, 0x4f, 0x54, 0x25, 0x22, 0xb8, 0x9c, 0xef, 0xa5,
	0xa1, 0x74, 0x84, 0xa9, 0xc3, 0x2d, 0x40, 0x42, 0xd9, 0x87, 0xda, 0xe8, 0x84, 0x32, 0x9c, 0x80,
	0x9d, 0xa7, 0x66, 0x8e, 0x2b, 0xec, 0xae, 0x4e, 0xbb, 0xab, 0x73, 0x0e, 0xde, 0xa1, 0xd6, 0x22,
	0x8b, 0xc6, 0x43, 0xdb, 0x38, 0x33, 0xb9, 0x17, 0x4c, 0xdf, 0x30, 0x7e, 0x97, 0xfc, 0x67, 0x58,
	0x73, 0xf0, 0x88, 0x97, 0x05, 0x7f, 0xe6, 0x4a, 0x36, 0x91, 0xb5, 0x8d, 0xca, 0xac, 0xde, 0x6c,
	0x48, 0x72, 0x63, 0xa2, 0x41, 0x61, 0x09, 0x93, 0xd3, 0xf0, 0xff, 0x88, 0x05, 0x9f, 0x60, 0xb0,
	0xaf, 0x63, 0xf1, 0xdd, 0xc0, 0x89, 0x46, 0x8b, 0x51, 0xdc, 0xc6, 0x24, 0x4e, 0x6f, 0x8b, 0x02,
	0xa0, 0x3d, 0x0c, 0x7c, 0x05, 0x68, 0xf7, 0x83, 0x18, 0x5f, 0xdd, 0xc7, 0xec, 0x3e, 0xbe, 0x5e,
	0x60, 0xd8, 0xc3, 0x67, 0xe8, 0xd7, 0xea, 0x71, 0x12, 0x77, 0x32, 0x9a, 0xdd, 0xc6, 0x5d, 0x5b,
	0x61, 0x6f, 0xd5, 0x37, 0xf7, 0xf7, 0xf2, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xab, 0x17, 0xce,
	0x93, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DlMsgBoard service

type DlMsgBoardClient interface {
	PublishMsg(ctx context.Context, in *PublishMsgRequest, opts ...client.CallOption) (*PublishMsgResponse, error)
	GetMsg(ctx context.Context, in *GetMsgRequest, opts ...client.CallOption) (*GetMsgResponse, error)
}

type dlMsgBoardClient struct {
	c           client.Client
	serviceName string
}

func NewDlMsgBoardClient(serviceName string, c client.Client) DlMsgBoardClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "dlmsgboard"
	}
	return &dlMsgBoardClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dlMsgBoardClient) PublishMsg(ctx context.Context, in *PublishMsgRequest, opts ...client.CallOption) (*PublishMsgResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DlMsgBoard.PublishMsg", in)
	out := new(PublishMsgResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dlMsgBoardClient) GetMsg(ctx context.Context, in *GetMsgRequest, opts ...client.CallOption) (*GetMsgResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DlMsgBoard.GetMsg", in)
	out := new(GetMsgResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DlMsgBoard service

type DlMsgBoardHandler interface {
	PublishMsg(context.Context, *PublishMsgRequest, *PublishMsgResponse) error
	GetMsg(context.Context, *GetMsgRequest, *GetMsgResponse) error
}

func RegisterDlMsgBoardHandler(s server.Server, hdlr DlMsgBoardHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DlMsgBoard{hdlr}, opts...))
}

type DlMsgBoard struct {
	DlMsgBoardHandler
}

func (h *DlMsgBoard) PublishMsg(ctx context.Context, in *PublishMsgRequest, out *PublishMsgResponse) error {
	return h.DlMsgBoardHandler.PublishMsg(ctx, in, out)
}

func (h *DlMsgBoard) GetMsg(ctx context.Context, in *GetMsgRequest, out *GetMsgResponse) error {
	return h.DlMsgBoardHandler.GetMsg(ctx, in, out)
}
